# Generated by Django 4.2.9 on 2024-01-06 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('audi', 'Audi'), ('bmv', 'BMV'), ('chevrolet', 'Chevrolet'), ('dodge', 'Dodge'), ('Fiat', 'Fiat'), ('ford', 'Ford'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('mercedes', 'Mercedes'), ('mini cooper', 'Mini Cooper'), ('nissan', 'Nissan'), ('renault', 'Renault'), ('suzuki', 'Suzuki'), ('tesla', 'Tesla'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo')], max_length=20)),
                ('model', models.CharField(max_length=300)),
                ('year', models.IntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005')], default=2024)),
                ('fuel', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ethanol', 'Ethanol'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=5)),
                ('engine_size', models.CharField(max_length=10)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('drivetrain', models.CharField(choices=[('front-wheel', 'Front-wheel'), ('rear-wheel', 'Rear-wheel'), ('four-wheel', 'Four-wheel')], max_length=15)),
                ('mileage', models.CharField(choices=[('0 - 500', '0 - 500'), ('500 - 1500', '500 - 1500'), ('2000 - 4000', '2000 - 4000'), ('5000 - 7000', '5000 - 7000'), ('7500 - 10.000', '7500 - 10.000'), ('11.000 - 13.000', '11.000 - 13.000'), ('14.000 - 16.000', '14.000 - 16.000'), ('17.000 - 19.000', '17.000 - 19.000'), ('20.000+', '20.000+')], max_length=25)),
                ('price', models.CharField(max_length=15)),
                ('hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=66, message='Invalid input, the value is too low'), django.core.validators.MaxValueValidator(limit_value=2012, message='Invalid input, value to high')])),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('cabriolet', 'Cabriolet'), ('wagon', 'Wagon'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('compact', 'Compact'), ('truck', 'Truck'), ('minivan', 'Minivan')], max_length=10)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1000, None], upload_to='reviews/')),
                ('image_alt', models.CharField(max_length=100)),
                ('drivingexp', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('acceleration', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('comfort', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('safety', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('practicality', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('interior', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('ergonomics', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('pros', djrichtextfield.models.RichTextField(max_length=350)),
                ('cons', djrichtextfield.models.RichTextField(max_length=350)),
                ('additional', djrichtextfield.models.RichTextField(blank=True, max_length=1500, null=True)),
                ('summary', djrichtextfield.models.RichTextField(max_length=500)),
                ('overall', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
